Member can show off different projects they have done in their profile
CraftAcademyLabs/ca_outboarding pull request #15
Opened 2018-11-08 15:17 UTC by oliverochman

2018-11-13 05:23 UTC, tochman approved these changes
Good job @oliverochman Is this still WIP?

2018-11-14 15:35 UTC, magnus-thor requested changes

2018-11-14 15:35 UTC, magnus-thor commented on app/models/resource.rb
> +  validates_presence_of :url, :of_type
Please validate the presence of description

2018-11-14 15:39 UTC, magnus-thor approved these changes

2018-11-14 15:39 UTC, merged